### ISSUE TITLE
Whitelist (request)

### ISSUE THREAD

**Issue by youurayy** [bigspaceship/Clear-Cache-Extension#1]
Hi, do you think you could add a whitelist for some sites?

I love to clean the cookie mess, but I really hate when I then have to re-login to all the good sites I use - google, basecamp, github, facebook, etc. etc. - that's just endless password unlocking via Keychain Access (on mac).

It would be the best extension:)

**Comment by benjaminbojko** [comment]
That's an interesting thought. This extension wasn't really built for that but it's definitely worth a consideration. What use-case is more likely for you: Clearing cookies for all sites except for a few or clearing cookies for specific sites only?

**Comment by youurayy** [comment]
Clearing cookies for all the websites that don't use those cookies to help me (keep me logged in), but to help themselves (track me).

In other words, clearing cookies for all sites except for a few.

Thanks so much for considering this! I wish I could help myself but I'm very stretched at this time.

**Comment by benjaminbojko** [comment]
I played around with the cookie API a little and came up with a version that has white-/blacklisting for certain domains enabled. Unfortunately the API isn't quite as flexible as I would have hoped so filtering by domains is a little tricky if you want to cover all subdomains at once, for example.

You can download the beta here:

https://github.com/downloads/bigspaceship/Clear-Cache-Extension/clear-cache-0.1.6-beta1.crx

I'd love to hear what you think. This version seems stable to me but frankly I haven't had the opportunity to use the cookie feature on an actual project yet.

Note that this update will not clear any localStorage data since the API only gives direct access to cookies.

**Comment by youurayy** [comment]
Hi, I checked your [code](https://github.com/bigspaceship/Clear-Cache-Extension/blob/master/src/js/backgroundpage.js) and then the [API](http://code.google.com/chrome/extensions/experimental.clear.html), and it seems like the whitelisting is not possible to implement.
Only if the browser somehow allowed you to read all the cookies, and then programmatically clear one by one, except those you want to keep.
Do I understand that correctly?

**Comment by benjaminbojko** [comment]
Yes, that's exactly how I see it.

You were looking at the code in the [master branch](https://github.com/bigspaceship/Clear-Cache-Extension) though. Below is the code that I used for the 1.6-beta1 version that I posted above (in the [cookie-filters](https://github.com/bigspaceship/Clear-Cache-Extension/tree/cookie-filters) branch).

https://github.com/bigspaceship/Clear-Cache-Extension/blob/cookie-filters/src/js/backgroundpage.js

If you install the beta you'll have the option to whitelist pages, which is going to work exactly how you described it, or blacklist pages, which will work a lot faster since you can filter cookies by domains and only clear as many domains as you defined. To access those settings you can click on the little wrench next to the Cookies label.

Like I said, it's still not anywhere close to as elegant as I had hoped for, but it would do the job.

**Comment by youurayy** [comment]
Ah OK, I was looking at the wrong branch. The code in the cookie branch looks good. Give me a few days to compile my whitelist and then I'll try it out. My Chrome cache cleaning is long overdue already. Thanks!

**Comment by benjaminbojko** [comment]
Great, thanks for your help. I just found out that they're in the midst of finalizing the API and it might be released in the near future (weeks or months, I assume). They're also thinking about adding domain-based filtering to the entire clear API, which would make our lives a _lot_ easier.

**Comment by benjaminbojko** [comment]
The cookie filters have been added to version 0.2.
